name: Build

on:
  # trigger on pushes
  push:
    branches: [ main ]
  # trigger on PRs
  pull_request:
    branches: main
  # trigger weekly, as far as tensorflow:latest-gpu is used
  schedule:
    - cron: '5 9 * * SAT'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub (TensorFlow)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lnstadrum/fastaugment_tf:latest
          file: ./tensorflow.Dockerfile

      - name: Push to Docker Hub (PyTorch)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lnstadrum/fastaugment_torch:latest
          file: ./pytorch.Dockerfile
