on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to Docker Hub (TensorFlow)
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lnstadrum/fastaugment
          file: ./tensorflow.Dockerfile
          tag_with_ref: true

      - name: Push to Docker Hub (PyTorch)
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lnstadrum/fastaugment
          file: ./pytorch.Dockerfile
          tag_with_ref: true
